server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  info:
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "INFO"}' http://localhost:8765/actuator/loggers/ROOT
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers
