name: Gradle Build & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.7
    with:
      flow-type: hybrid
      java-version: '21'
      docker-image: api-gateway
