name: Gradle Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@gradle-templates
    with:
      java-version: "11"
      docker-image: false
