name: Gradle release

on: workflow_dispatch

jobs:
  build-release-publish:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@gradle-templates
    with:
      java-version: "11"
      docker-image: false
    secrets: inherit
