name: Gradle release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@gradle-templates
    secrets: inherit
    with:
      java-version: "11"
      docker-image: false
